-- AlterTable
ALTER TABLE `Item` ADD COLUMN `orderIndex` DOUBLE NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `Session` MODIFY `expiresAt` DATETIME(3) NOT NULL DEFAULT DATE_ADD(NOW(), INTERVAL 30 DAY);
